### ISSUE TITLE
Оновити розділ "Формати файлів"

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [miroslava271/practuka#6]
Дайти приклад файлів різних форматів (csv, json, xml) - бо краще один раз побачити.

Скажи в чому переваги одного перед одним? де б ти використовував кожен з цих форматів?

Чого для логів ми взяли формат csv? а для історії перемог - json?

**Comment by miroslava271** [comment]
### 1. Приклад файлів різних форматів:
_CSV:_
```
Name,Age,City
Myra,17,Chernihiv
Ulyana,17,Prague
```
**Переваги**: Простота у використанні інтерфейсу, підтримка багатьох програм, швидкий та ефективний для обробки великих обсягів даних.
**Використання**: Зазвичай використовується для зберігання табличних даних, таких як дані з баз даних, реєстри, тощо. Також може бути корисним для обміну даними між різними програмами.

_JSON:_
```
{
  "players": [
    {
      "name": "Myra",
      "age": 17,
      "city": "Chernihiv"
    },
    {
      "name": "Ulyana",
      "age": 17,
      "city": "Prague"
    }
  ]
}
```
**Переваги**: Гнучкість у представленні структурованих даних, легкість для читання та розуміння людиною, підтримка вкладених об'єктів та масивів.
**Використання**: Широко використовується для зберігання конфігурацій, обміну даними між сервером та клієнтом у веб-додатках.

_XML:_
```
<players>
  <player>
    <name>Myra</name>
    <age>17</age>
    <city>Chernihiv</city>
  </player>
  <player>
    <name>Ulyana</name>
    <age>17</age>
    <city>Prague</city>
  </player>
</players>
```
**Переваги**: Розширюваність та можливість створення власних тегів, підтримка вкладених структур даних, підтримка різних кодувань символів.
**Використання**: Застосовується в багатьох сферах, таких як розмітка документів у веб-розробці, обмін даними між різними системами, конфігураційні файли.

### Чого для логів ми взяли формат csv? а для історії перемог - json?
На мою думку ми обрали формат csv, та json тому що **csv** - це хороший вибір для логів через його простоту та легкість відображення табличних даних, які зазвичай містяться у логах, а **json** може бути корисним для зберігання структурованих даних, таких як дані про ігрові перемоги, оскільки він може представити вкладені структури та об'єкти, що можуть бути легко оброблені програмно.

**Comment by AnatoliiStepaniuk** [comment]
додай це в звіт плз
