### ISSUE TITLE
оновити розділ VСS

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [miroslava271/practuka#7]
дай приклад команд які для тебе найкорисніші в GIT

Опиши Git Flow з картинками

**Comment by miroslava271** [comment]
### Приклади:

1. git init: Ініціалізує порожній репозиторій Git у поточному каталозі.
2. git clone <URL>: Клонує віддалений репозиторій на локальний комп'ютер.
3. git add <file>: Додає зміни файлу до індексу для подальшого коміту.
4. git pull: Витягує та об'єднує зміни з віддаленого репозиторію у локальний.
5. git push: Відправляє локальні коміти на віддалений репозиторій.
6. git status: Показує статус змін у вашому репозиторії.
7. git log: Показує історію комітів у репозиторії.

### Git Flow:
![image](https://github.com/miroslava271/practuka/assets/145108203/6c3a3fa7-2dc5-4f63-80ed-02e949b046c4)

**main**: Гілка main відображає продуктовий код. Кожен коміт у main повинен відповідати випущеній версії програми.

**develop**: Гілка develop є основною робочою гілкою, де розробляється новий код. Всі функціональність, що входить до наступного випуску, повинні бути злиті у цю гілку.

**feature branches**: Кожна нова функціональність або фіча розробляється у власній гілці, яка виходить з develop. Після завершення роботи над функціоналом гілка зливається назад у develop.

**release branches**: Коли розробники готові до випуску нової версії програми, вони створюють гілку release з develop. У цій гілці вони можуть виконати остаточні тести та виправлення перед випуском нової версії.

**hotfix branches**: Гілки hotfix використовуються для виправлення критичних помилок у продукції, які виявляються в main. Ці гілки виходять з main, виправляють помилки та зливаються як у main, так і в develop.

**Comment by AnatoliiStepaniuk** [comment]
@miroslava271 😁
це все вірно, але чого це не в звіті))) в кінці кінців оцінюється звіт, а не коментарі в issue)
