### ISSUE TITLE
Оновити розділ Markdown

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [miroslava271/practuka#8]
Додай ще прикладів синтаксису в Markdown. їх там не так багато. можеш перелічити всі

**Comment by miroslava271** [comment]
### 1.Заголовки:
# Заголовок першого рівня
## Заголовок другого рівня
### Заголовок третього рівня
### 2.Текст:
*Курсив*
**Напівжирний**
***Курсив та напівжирний***
`Код`
### 3.Списки:
- Елемент списку 1
- Елемент списку 2
  - Вкладений елемент списку
1. Елемент списку з номером 1
2. Елемент списку з номером 2
### 4.Посилання:
[Текст посилання](https://www.example.com)
### 5.Зображення:
![Опис зображення](https://www.example.com/image.jpg)
### 6.Таблиці:
| Заголовок 1 | Заголовок 2 |
|-------------|-------------|
| Вміст 1     | Вміст 2     |
### 7.Цитати:
> Це цитата.
### 8.Горизонтальні лінії:
---
### 9.Видалення та підкреслення:
~~Видалено~~
<u>Підкреслено</u>

**Comment by AnatoliiStepaniuk** [comment]
це треба в звіті)

**Comment by miroslava271** [comment]
Звіт оновила
